; Listing generated by Microsoft (R) Optimizing Compiler Version 19.12.25831.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\asus\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.cpp"
